### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by glb** [iRobotCorporation/cfn-custom-resource#6]
There's no license listed, could you please clarify under what terms this is shared?

https://help.github.com/articles/licensing-a-repository/
"[...] without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work."

https://help.github.com/articles/adding-a-license-to-a-repository/

Thanks!

**Comment by benkehoe** [comment]
It's under the MPL as shown here https://github.com/iRobotCorporation/cfn-custom-resource/blob/master/cfn_custom_resource/cfn_custom_resource.py#L35 but that hasn't been copied around as it has grown beyond that single file.

**Comment by benkehoe** [comment]
Added LICENSE file
